<?php
require_once("autoloader.php");

$lista = new Model;
$conn = $lista->getConn(); // Obtener la conexión a la base de datos
$id = $_GET['id']; // Obtener el ID de la tarea desde la URL
$sql = "SELECT * FROM tareas WHERE id = ". $id ." ;" ;
$stmt = $conn->prepare($sql);
$stmt->execute();
$row = $stmt->fetch(PDO::FETCH_ASSOC); //  Obtener el resultado (la fila de la tarea)
$title = $row['titulo'];
$descripcion = $row['descripcion']; 
$dueDate = $row['fecha_vencimiento']; // Obtener la fecha de vencimiento
if(count($_POST) > 0){
	$lista = new Model;
	$lista->updateTarea($_POST);
	header("Location: index.php"); // Redirige a index.php después de guardar
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Nueva Tarea</title>
<link rel="stylesheet" type="text/css" href="form/view.css" media="all">
</head>
<body id="main_body">
	
	<img id="top" src="form/top.png" alt="">
	<div id="form_container">
	
		<h1><a>Nueva Tarea</a></h1>
		<form class="appnitro"  method="post" action="">
					<div class="form_description">
			<h2>Nueva Tarea</h2>
			<p>Introduce los datos de la tarea</p>
		</div>						
			<ul >
			
					<li>
		<label class="description" for="title">Titulo </label>
		<div>
			<input name="titulo" class="element text medium" type="text" maxlength="255" value="<?= $title?>"/> 
		</div> 
		</li>		<li>
		<label class="description" for="description">Descripción de la tarea  </label>
		<div>
			<textarea name="descripcion" class="element textarea medium" ><?=$descripcion?></textarea> 
		</div> 
		</li>		<li>
		<label class="description" for="dueDate"><?php $row['fecha_vencimiento']; ?></label>
		<span>
			<input name="fecha_vencimiento" class="element text" size="2" maxlength="2" value="<?=$dueDate?>" type="date">
		</span>	 
		</li>
			
		<li class="buttons">
			    <input type="hidden" name="id" value="<?= $id ?>" />
				<input class="button_text" type="submit" name="submit" value="Guardar" />
		</li>
			</ul>
		</form>	
        <a href= "index.php">Volver</a>
		<div id="footer">
			Generated by <a href="http://www.floridauniversitaria.es">Florida</a>
		</div>
	</div>
	<img id="bottom" src="form/bottom.png" alt="">
	</body>
</html>